from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT, WD_LINE_SPACING
from docx.oxml.ns import qn

def create_professional_template(output_path):
    doc = Document()
    
    # --- Update Normal Style ---
    style = doc.styles['Normal']
    font = style.font
    font.name = 'Arial'  # Clean, professional sans-serif
    font.size = Pt(10.5)
    font.color.rgb = RGBColor(50, 50, 50) # Dark Charcoal, softer than pure black
    # East Asia font for Chinese
    style._element.rPr.rFonts.set(qn('w:eastAsia'), 'Microsoft YaHei')
    
    # Paragraph format
    pf = style.paragraph_format
    pf.line_spacing_rule = WD_LINE_SPACING.MULTIPLE
    pf.line_spacing = 1.3 # Airy reading experience
    pf.space_after = Pt(10)
    
    # --- Update Heading 1 (Title of sections) ---
    # McKinsey/Goldman style: Often distinct, clear hierarchy
    h1 = doc.styles['Heading 1']
    h1.font.name = 'Arial'
    h1.font.size = Pt(18)
    h1.font.bold = True
    h1.font.color.rgb = RGBColor(0, 51, 102) # Deep Navy Blue
    h1._element.rPr.rFonts.set(qn('w:eastAsia'), 'Microsoft YaHei')
    h1.paragraph_format.space_before = Pt(24)
    h1.paragraph_format.space_after = Pt(12)
    # Add a bottom border to Heading 1 for separation (requires OXML, skipping for simplicity unless essential, 
    # but color distinction is usually enough)
    
    # --- Update Heading 2 ---
    h2 = doc.styles['Heading 2']
    h2.font.name = 'Arial'
    h2.font.size = Pt(14)
    h2.font.bold = True
    h2.font.color.rgb = RGBColor(0, 85, 150) # Medium Blue
    h2._element.rPr.rFonts.set(qn('w:eastAsia'), 'Microsoft YaHei')
    h2.paragraph_format.space_before = Pt(18)
    h2.paragraph_format.space_after = Pt(8)

    # --- Update Heading 3 ---
    h3 = doc.styles['Heading 3']
    h3.font.name = 'Arial'
    h3.font.size = Pt(12)
    h3.font.bold = True
    h3.font.color.rgb = RGBColor(80, 80, 80) # Dark Grey
    h3._element.rPr.rFonts.set(qn('w:eastAsia'), 'Microsoft YaHei')
    h3.paragraph_format.space_before = Pt(12)
    h3.paragraph_format.space_after = Pt(6)

    # --- List Styles ---
    # Note: Modifying 'List Bullet' directly in python-docx can be tricky if not already present.
    # We access it to ensure it exists or modify properties.
    try:
        if 'List Bullet' in doc.styles:
            lb = doc.styles['List Bullet']
            lb.font.name = 'Arial'
            lb.font.size = Pt(10.5)
            lb.paragraph_format.line_spacing = 1.3
    except:
        pass

    # --- Quote Style ---
    # Attempt to style 'Quote'
    try:
        if 'Quote' in doc.styles:
            qs = doc.styles['Quote']
            qs.font.name = 'Arial'
            qs.font.italic = True
            qs.font.color.rgb = RGBColor(100, 100, 100)
            qs.paragraph_format.left_indent = Inches(0.5)
            qs.paragraph_format.right_indent = Inches(0.5)
    except:
        pass

    # --- Header ---
    # Add a header with "CONFIDENTIAL" text
    section = doc.sections[0]
    header = section.header
    paragraph = header.paragraphs[0]
    paragraph.text = "CONFIDENTIAL | FOR DISCUSSION PURPOSES ONLY"
    paragraph.alignment = WD_PARAGRAPH_ALIGNMENT.RIGHT
    run = paragraph.runs[0]
    run.font.name = 'Arial'
    run.font.size = Pt(8)
    run.font.color.rgb = RGBColor(150, 150, 150)
    
    # --- Footer ---
    footer = section.footer
    p_foot = footer.paragraphs[0]
    p_foot.text = "Generated by MD2DOCX | Professional Report"
    p_foot.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
    run_foot = p_foot.runs[0]
    run_foot.font.name = 'Arial'
    run_foot.font.size = Pt(8)
    run_foot.font.color.rgb = RGBColor(180, 180, 180)

    # --- Page Setup ---
    # Wide margins for a premium feel
    section.top_margin = Inches(1.2)
    section.bottom_margin = Inches(1.2)
    section.left_margin = Inches(1.2)
    section.right_margin = Inches(1.2)

    doc.save(output_path)
    print(f"Template saved to {output_path}")

if __name__ == "__main__":
    create_professional_template("professional_template.docx")
