from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT, WD_LINE_SPACING
from docx.oxml.ns import qn
import os

def set_font(style, font_name, east_asia_font=None):
    font = style.font
    font.name = font_name
    if east_asia_font:
        style._element.rPr.rFonts.set(qn('w:eastAsia'), east_asia_font)

def create_professional_template(output_path):
    doc = Document()
    ea_font = 'Microsoft YaHei'
    main_font = 'Arial'

    # Normal Style
    style = doc.styles['Normal']
    set_font(style, main_font, ea_font)
    style.font.size = Pt(10.5)
    style.font.color.rgb = RGBColor(50, 50, 50)
    pf = style.paragraph_format
    pf.line_spacing = 1.3
    pf.space_after = Pt(10)

    # Headings
    h1 = doc.styles['Heading 1']
    set_font(h1, main_font, ea_font)
    h1.font.size = Pt(18)
    h1.font.bold = True
    h1.font.color.rgb = RGBColor(0, 51, 102)
    h1.paragraph_format.space_before = Pt(24)
    h1.paragraph_format.space_after = Pt(12)

    h2 = doc.styles['Heading 2']
    set_font(h2, main_font, ea_font)
    h2.font.size = Pt(14)
    h2.font.bold = True
    h2.font.color.rgb = RGBColor(0, 85, 150)
    h2.paragraph_format.space_before = Pt(18)
    h2.paragraph_format.space_after = Pt(8)

    # Header/Footer
    section = doc.sections[0]
    section.header.paragraphs[0].text = "CONFIDENTIAL | PROFESSIONAL REPORT"
    section.footer.paragraphs[0].text = "Generated by md2docx"
    
    doc.save(output_path)
    print(f"Created {output_path}")

def create_academic_template(output_path):
    doc = Document()
    ea_font = 'SimSun' # Standard for Chinese academic papers
    main_font = 'Times New Roman'

    # Normal Style
    style = doc.styles['Normal']
    set_font(style, main_font, ea_font)
    style.font.size = Pt(12)
    pf = style.paragraph_format
    pf.line_spacing = 1.5 # Double spacing or 1.5 is common
    pf.first_line_indent = Inches(0.5)

    # Headings (Centered H1)
    h1 = doc.styles['Heading 1']
    set_font(h1, main_font, ea_font)
    h1.font.size = Pt(16)
    h1.font.bold = True
    h1.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER

    h2 = doc.styles['Heading 2']
    set_font(h2, main_font, ea_font)
    h2.font.size = Pt(14)
    h2.font.bold = True

    doc.save(output_path)
    print(f"Created {output_path}")

def create_creative_template(output_path):
    doc = Document()
    ea_font = 'Microsoft YaHei'
    main_font = 'Trebuchet MS'

    # Normal Style
    style = doc.styles['Normal']
    set_font(style, main_font, ea_font)
    style.font.size = Pt(11)
    style.font.color.rgb = RGBColor(60, 60, 60)

    # Headings (Colorful)
    h1 = doc.styles['Heading 1']
    set_font(h1, main_font, ea_font)
    h1.font.size = Pt(22)
    h1.font.color.rgb = RGBColor(255, 102, 0) # Orange

    h2 = doc.styles['Heading 2']
    set_font(h2, main_font, ea_font)
    h2.font.size = Pt(18)
    h2.font.color.rgb = RGBColor(0, 153, 204) # Sky Blue

    doc.save(output_path)
    print(f"Created {output_path}")

if __name__ == "__main__":
    create_professional_template("professional_template.docx")
    create_academic_template("academic_template.docx")
    create_creative_template("creative_template.docx")
